# Generated by Django 5.1.5 on 2025-01-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
