# Generated by Django 5.1.5 on 2025-01-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
